const categories = ["OVERGROWN LOT", "TREE TRIM AND ROOT PRUNING", "DEAD ANIMAL PICKUP", "ROAD DEBRIS BLOCKING TRAFFIC RIGHT OF WAY", "GRAFFITI", "ILLEGAL STORAGE / JUNK IN YARD", "LANDSCAPING CITY RIGHT OF WAY / MOWING"]

export default categories